include_guard(GLOBAL)

set(RECOMP_DXC_EXECUTABLE "" CACHE FILEPATH
    "Path to dxc; only used by explicit <target>_shaders regeneration targets")

function(recomp_add_shaders target)
    cmake_parse_arguments(SHADERS "" "ENTRY_POINT" "SOURCES;INCLUDE_DIRS" ${ARGN})

    if(NOT TARGET ${target})
        message(FATAL_ERROR "recomp_add_shaders: '${target}' is not a target")
    endif()
    if(NOT SHADERS_SOURCES)
        message(FATAL_ERROR "recomp_add_shaders(${target}) requires SOURCES")
    endif()
    if(NOT SHADERS_ENTRY_POINT)
        set(SHADERS_ENTRY_POINT main)
    endif()

    string(MAKE_C_IDENTIFIER "${target}" shader_namespace)
    set(generated_dir "${CMAKE_CURRENT_BINARY_DIR}/generated/recomp_shaders")
    set(index_header "${generated_dir}/${target}_shaders.h")
    set(index_content
        "// Generated by recomp_add_shaders -- DO NOT EDIT\n#pragma once\n\n#include <cstdint>\n#include <span>\n#include <string_view>\n\nnamespace recomp::shaders::${shader_namespace} {\nstruct EmbeddedShader {\n  std::string_view hlsl;\n  std::span<const uint8_t> dxil;\n  std::string_view entry_point;\n};\n}  // namespace recomp::shaders::${shader_namespace}\n")
    set(generated_headers "")
    set(bytecode_commands "")

    set(shader_include_dirs "${CMAKE_CURRENT_SOURCE_DIR}")
    foreach(include_dir IN LISTS SHADERS_INCLUDE_DIRS)
        cmake_path(ABSOLUTE_PATH include_dir BASE_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
                   NORMALIZE OUTPUT_VARIABLE absolute_include_dir)
        list(APPEND shader_include_dirs "${absolute_include_dir}")
    endforeach()
    list(REMOVE_DUPLICATES shader_include_dirs)

    set(shader_include_dependencies "")
    foreach(include_dir IN LISTS shader_include_dirs)
        file(GLOB_RECURSE include_files CONFIGURE_DEPENDS "${include_dir}/*.hlsli")
        list(APPEND shader_include_dependencies ${include_files})
    endforeach()
    list(REMOVE_DUPLICATES shader_include_dependencies)

    foreach(shader IN LISTS SHADERS_SOURCES)
        cmake_path(ABSOLUTE_PATH shader BASE_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
                   NORMALIZE OUTPUT_VARIABLE shader_path)
        get_filename_component(shader_filename "${shader_path}" NAME)
        if(NOT shader_filename MATCHES "^(.+)\\.(vs|ps|cs)\\.hlsl$")
            message(FATAL_ERROR
                "recomp_add_shaders: '${shader}' must end in .vs.hlsl, .ps.hlsl or .cs.hlsl")
        endif()
        set(shader_name "${CMAKE_MATCH_1}")
        set(shader_stage "${CMAKE_MATCH_2}")
        set(shader_profile "${shader_stage}_6_0")
        get_filename_component(shader_dir "${shader_path}" DIRECTORY)
        set(dxil_path "${shader_dir}/${shader_name}.${shader_stage}.dxil")

        file(RELATIVE_PATH shader_relative "${CMAKE_CURRENT_SOURCE_DIR}" "${shader_path}")
        string(MAKE_C_IDENTIFIER "${shader_relative}" shader_identifier)
        set(shader_header "${generated_dir}/${shader_identifier}.h")
        list(APPEND generated_headers "${shader_header}")

        string(JOIN "|" include_dirs_arg ${shader_include_dirs})
        add_custom_command(
            OUTPUT "${shader_header}"
            COMMAND ${CMAKE_COMMAND}
                "-DSHADER_SOURCE=${shader_path}"
                "-DSHADER_DXIL=${dxil_path}"
                "-DSHADER_OUTPUT=${shader_header}"
                "-DSHADER_NAMESPACE=${shader_namespace}"
                "-DSHADER_IDENTIFIER=${shader_identifier}"
                "-DSHADER_ENTRY_POINT=${SHADERS_ENTRY_POINT}"
                "-DSHADER_INCLUDE_DIRS=${include_dirs_arg}"
                -P "${RECOMP_ROOT}/cmake/EmbedShader.cmake"
            DEPENDS "${shader_path}" "${dxil_path}" ${shader_include_dependencies}
                    "${RECOMP_ROOT}/cmake/EmbedShader.cmake"
            COMMENT "Embedding ${shader_relative}"
            VERBATIM)
        string(APPEND index_content "#include \"${shader_identifier}.h\"\n")

        list(APPEND bytecode_commands
            COMMAND ${CMAKE_COMMAND}
                "-DDXC_EXECUTABLE=${RECOMP_DXC_EXECUTABLE}"
                "-DSHADER_SOURCE=${shader_path}"
                "-DSHADER_OUTPUT=${dxil_path}"
                "-DSHADER_PROFILE=${shader_profile}"
                "-DSHADER_ENTRY_POINT=${SHADERS_ENTRY_POINT}"
                "-DSHADER_INCLUDE_DIRS=${include_dirs_arg}"
                -P "${RECOMP_ROOT}/cmake/CompileShaderDxil.cmake")
    endforeach()

    file(MAKE_DIRECTORY "${generated_dir}")
    file(GENERATE OUTPUT "${index_header}" CONTENT "${index_content}")
    target_sources(${target} PRIVATE "${index_header}" ${generated_headers})
    target_include_directories(${target} PRIVATE "${generated_dir}")

    add_custom_target(${target}_shaders ${bytecode_commands}
        COMMENT "Regenerating committed DXIL for ${target}"
        VERBATIM)
endfunction()
